### ISSUE TITLE
Merge forces 😊

### ISSUE THREAD

**Issue by joantune** [nestjs-shopify/nestjs-shopify#285]
Hi guys!

I'm pleasantly surprised to have learned about this repository

At Sounds Good Agency ( SGA - https://www.soundsgood.agency/) we're developing something similar and we were wondering if we ought to open source it or not - after seeing this it became obvious it might be a great idea to join forces.

We are working with the Firebase (GCP based) stack:

Firebase functions
Firestore
Firebase hosting
Google tasks

and it might be interesting to share codebases etc - especially given how Nest.JS is modular

Right now we're at a crossroads of investing more time with our framework and/or changing to Shopify's Remix new direction

anyway - I would love to hear what's your availability and openness to join forces and codebases - pluse I have some ideas on how to make this O.S. project more sustainable

if anyone is open to this from your end - I would love to talk about it

Let me know here and we can arrange a call and/or keep it async and/or add you guys (or some of you) to our Slack

LMK

- Joao
(CTO at SGA)

**Comment by tolgap** [comment]
Hi @joantune thank you very much for the kind words!

The reason I built the `nestjs-shopify` package is because I'm needed it professionally. I am not a full time maintainer of any open source project. But of course, I always welcome contributions 😄 .

I am in no position currently to dedicate time for such endeavors. If in any case you need more features or fixes to this package I would urge anyone to submit issues for them and in the best scenario open PRs for them.

If someone at Sounds Good wants more commitment of this project, I would be able to add maintainers to this project to work directly on the code base. But I would like to maintain the final "merge".

The packages have MIT licenses so if Sounds Good wants to maintain their own fork, and push features/fixes upstream to this package, I would be happy to go through them as well.

Best,
Tolga

**Comment by joantune** [comment]
Lack of resources is a common issue - I think we can come up with a better solution to alleviate this. I'm sure people are interested and maybe even some people would pay to see feature X added etc - especially if we demonstrate what the platform can be good for.

I am slowly coming up with some ideas here - and will include you in any future progress that is made.

I appreciate the effort in the name of everyone - but I think it's also the major general issue in open source that it can take a clue from capitalism and use its resource allocation functionality (money) which isn't necessarily incompatible with an open source license
